#!/usr/bin/python3 -xv
# SPDX-FileCopyrightText: 2024 Masaya Kobayashi
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans ,a,b,c= 1.0 ,0,float(input()),float(input())

while a <= c-1:
    ans *= b
    a += 1

print(ans)
